# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-04 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=b'', max_length=100)),
                ('code', models.TextField(help_text=b'code model help text')),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[(b'cpp', b'cpp'), (b'js', b'js'), (b'python', b'python')], default=b'python', max_length=100)),
                ('style', models.CharField(choices=[(b'monokai', b'monokai'), (b'solarized-dark', b'solarized-dark'), (b'vim', b'vim')], default=b'solarized-dark', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='SnippetViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='snippets.Snippet')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
