# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-04 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'title model help_text', max_length=255, unique=True)),
                ('body', models.TextField(help_text=b'article model help_text', max_length=5000)),
                ('slug', models.SlugField(blank=True, help_text=b'slug model help_text', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('article_type', models.PositiveSmallIntegerField(choices=[(1, b'first'), (2, b'second'), (3, b'third'), (7, b'seven'), (8, b'eight')], help_text=b'IntegerField declared on model with choices=(...) and exposed via ModelSerializer', null=True)),
                ('cover', models.ImageField(blank=True, upload_to=b'article/original/')),
                ('read_only_nullable', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text=b'title model help_text', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text=b'slug model help_text', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='articles_as_main', to='articles.ArticleGroup'),
        ),
        migrations.AddField(
            model_name='article',
            name='original_group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='articles_as_original', to='articles.ArticleGroup'),
        ),
    ]
